# Add application configuration variables here, as shown below.
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS


MAILCHIMP: 0df6f13f2cdab5c67870e73f5d6ebcb7-us3
MAILCHIMP_LIST: 8afaedfb04